# MaCFP workflow

name: Liquid_Pool_Fires

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-line-endings:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Check for CFLF line endings
        run: |
          N_CRLF_FILES=$(grep -rl $'\r$' * > tmp.txt && cat tmp.txt | wc -l)
          echo $N_CRLF_FILES
          if [$N_CRLF_FILES -gt 0]
          then
            echo "FAIL: Windows (CRLF) line endings detected!"
            exit 1
          else
            echo "PASS: Unix (LF) line endings only"
          fi




